name: JavaScript
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  main_testing:
    name: Run tests and upload coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
      
      - name: Install dependencies
        run: npm ci

      - name: Run test with coverage
        run: npm run test:coverage

      - name: Upload coverage
        uses: coverallsapp/github-action@v2.3.6
